// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fftnljlqpghdlwqrrgae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdG5samxxcGdoZGx3cXJyZ2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNDQ2MDgsImV4cCI6MjA5MDkyMDYwOH0.ukFtur2rdSd6LJGr8shBrq4TXQ-IIREAg27gq7niriU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});